export const SET_LOG_IN = 'SET_LOG_IN';
export const RESET_STORE = 'RESET_STORE';
export const SIGN_UP_TYPE = 'SIGN_UP_TYPE';
export const FREE_TRIAL_SUBCOMPONENT= 'FREE_TRIAL_SUBCOMPONENT'
export const SET_STUDENT_SIGNUP_WITH_CLASS= 'SET_STUDENT_SIGNUP_WITH_CLASS'
